# $pdf_previewer = 'open -a Skim';
# $xelatex = "xelatex -synctex=1 -interaction=nonstopmode";
# $pdflatex = "xelatex -synctex=1 -interaction=nonstopmode";
# @generated_exts = (@generated_exts, 'synctex.gz');
# $cleanup_mode = 1;
# $preview_continuous_mode = 1;

$pdf_mode = 5;
$pdflatex=q/xelatex -synctex=1 %O %S/;
@default_files = ('main.tex');